/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#785a1a",
        "on-tertiary-container": "#838484",
        "tertiary": "#000000",
        "secondary-fixed": "#ffdea5",
        "on-tertiary-fixed-variant": "#454747",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "primary-fixed": "#e2e2e2",
        "surface-container": "#efeded",
        "error-container": "#ffdad6",
        "on-primary-container": "#848484",
        "on-tertiary-fixed": "#1a1c1c",
        "surface-container-low": "#f5f3f3",
        "on-background": "#1b1c1c",
        "tertiary-fixed-dim": "#c6c6c7",
        "surface-tint": "#5e5e5e",
        "surface-dim": "#dbdad9",
        "secondary-container": "#fed488",
        "on-secondary-fixed": "#261900",
        "primary": "#000000",
        "tertiary-fixed": "#e2e2e2",
        "on-tertiary": "#ffffff",
        "background": "#fbf9f9",
        "inverse-on-surface": "#f2f0f0",
        "on-primary-fixed-variant": "#474747",
        "surface-container-high": "#e9e8e7",
        "primary-container": "#1b1b1b",
        "on-surface-variant": "#4c4546",
        "outline-variant": "#cfc4c5",
        "inverse-surface": "#303031",
        "secondary-fixed-dim": "#e9c176",
        "surface-variant": "#e3e2e2",
        "surface-bright": "#fbf9f9",
        "tertiary-container": "#1a1c1c",
        "surface-container-highest": "#e3e2e2",
        "on-error": "#ffffff",
        "secondary": "#775a19",
        "on-primary": "#ffffff",
        "outline": "#7e7576",
        "inverse-primary": "#c6c6c6",
        "primary-fixed-dim": "#c6c6c6",
        "surface": "#fbf9f9",
        "on-surface": "#1b1c1c",
        "on-primary-fixed": "#1b1b1b",
        "on-secondary-fixed-variant": "#5d4201",
        "error": "#ba1a1a",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1440px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        unit: "8px",
        "section-gap": "120px",
        gutter: "32px",
      },
      fontFamily: {
        "body-lg": ["Montserrat", "sans-serif"],
        "display-lg-mobile": ["Bodoni Moda", "serif"],
        "body-md": ["Montserrat", "sans-serif"],
        "headline-md": ["Bodoni Moda", "serif"],
        "label-caps": ["Montserrat", "sans-serif"],
        "display-lg": ["Bodoni Moda", "serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "300" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.15em", fontWeight: "600" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
      maxWidth: {
        "container-max": "1440px",
      },
    },
  },
  plugins: [],
};
